post:
  description: Requests to enable bgp configuration for a project.
  operationId: requestBgpConfig
  parameters:
  - description: Project UUID
    in: path
    name: id
    required: true
    schema:
      format: uuid
      type: string
  - $ref: '../../../components/parameters/Include.yaml'
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../../components/schemas/BgpConfigRequestInput.yaml'
    description: BGP config Request to create
    required: true
  responses:
    "204":
      description: no content
    "401":
      content:
        application/json:
          schema:
            $ref: '../../../components/schemas/Error.yaml'
      description: unauthorized
    "403":
      content:
        application/json:
          schema:
            $ref: '../../../components/schemas/Error.yaml'
      description: forbidden
    "404":
      content:
        application/json:
          schema:
            $ref: '../../../components/schemas/Error.yaml'
      description: not found
    "422":
      content:
        application/json:
          schema:
            $ref: '../../../components/schemas/Error.yaml'
      description: unprocessable entity
  summary: Requesting bgp config
  tags:
  - BGP
