/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.fabric.v4.model;

import java.util.Objects;
import java.util.Arrays;
import com.equinix.openapi.fabric.v4.model.AWSDirectConnect;
import com.equinix.openapi.fabric.v4.model.AWSPermission;
import com.equinix.openapi.fabric.v4.model.AWSVirtualPrivateGateway;
import com.equinix.openapi.fabric.v4.model.TopologyProperties;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.UUID;

import javax.ws.rs.core.GenericType;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;

import com.equinix.openapi.fabric.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AWSProviderResource extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(AWSProviderResource.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!AWSProviderResource.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'AWSProviderResource' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<AWSDirectConnect> adapterAWSDirectConnect = gson.getDelegateAdapter(this, TypeToken.get(AWSDirectConnect.class));
            final TypeAdapter<AWSPermission> adapterAWSPermission = gson.getDelegateAdapter(this, TypeToken.get(AWSPermission.class));
            final TypeAdapter<AWSVirtualPrivateGateway> adapterAWSVirtualPrivateGateway = gson.getDelegateAdapter(this, TypeToken.get(AWSVirtualPrivateGateway.class));

            return (TypeAdapter<T>) new TypeAdapter<AWSProviderResource>() {
                @Override
                public void write(JsonWriter out, AWSProviderResource value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `AWSDirectConnect`
                    if (value.getActualInstance() instanceof AWSDirectConnect) {
                        JsonObject obj = adapterAWSDirectConnect.toJsonTree((AWSDirectConnect)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    // check if the actual instance is of the type `AWSPermission`
                    if (value.getActualInstance() instanceof AWSPermission) {
                        JsonObject obj = adapterAWSPermission.toJsonTree((AWSPermission)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    // check if the actual instance is of the type `AWSVirtualPrivateGateway`
                    if (value.getActualInstance() instanceof AWSVirtualPrivateGateway) {
                        JsonObject obj = adapterAWSVirtualPrivateGateway.toJsonTree((AWSVirtualPrivateGateway)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: AWSDirectConnect, AWSPermission, AWSVirtualPrivateGateway");
                }

                @Override
                public AWSProviderResource read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonObject jsonObject = elementAdapter.read(in).getAsJsonObject();

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize AWSDirectConnect
                    try {
                        // validate the JSON object to see if any exception is thrown
                        AWSDirectConnect.validateJsonObject(jsonObject);
                        actualAdapter = adapterAWSDirectConnect;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'AWSDirectConnect'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for AWSDirectConnect failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'AWSDirectConnect'", e);
                    }

                    // deserialize AWSPermission
                    try {
                        // validate the JSON object to see if any exception is thrown
                        AWSPermission.validateJsonObject(jsonObject);
                        actualAdapter = adapterAWSPermission;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'AWSPermission'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for AWSPermission failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'AWSPermission'", e);
                    }

                    // deserialize AWSVirtualPrivateGateway
                    try {
                        // validate the JSON object to see if any exception is thrown
                        AWSVirtualPrivateGateway.validateJsonObject(jsonObject);
                        actualAdapter = adapterAWSVirtualPrivateGateway;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'AWSVirtualPrivateGateway'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for AWSVirtualPrivateGateway failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'AWSVirtualPrivateGateway'", e);
                    }

                    if (match == 1) {
                        AWSProviderResource ret = new AWSProviderResource();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonObject));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for AWSProviderResource: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonObject.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, GenericType> schemas = new HashMap<String, GenericType>();

    public AWSProviderResource() {
        super("oneOf", Boolean.FALSE);
    }

    public AWSProviderResource(AWSDirectConnect o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public AWSProviderResource(AWSPermission o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public AWSProviderResource(AWSVirtualPrivateGateway o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("AWSDirectConnect", new GenericType<AWSDirectConnect>() {
        });
        schemas.put("AWSPermission", new GenericType<AWSPermission>() {
        });
        schemas.put("AWSVirtualPrivateGateway", new GenericType<AWSVirtualPrivateGateway>() {
        });
    }

    @Override
    public Map<String, GenericType> getSchemas() {
        return AWSProviderResource.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * AWSDirectConnect, AWSPermission, AWSVirtualPrivateGateway
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof AWSDirectConnect) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof AWSPermission) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof AWSVirtualPrivateGateway) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be AWSDirectConnect, AWSPermission, AWSVirtualPrivateGateway");
    }

    /**
     * Get the actual instance, which can be the following:
     * AWSDirectConnect, AWSPermission, AWSVirtualPrivateGateway
     *
     * @return The actual instance (AWSDirectConnect, AWSPermission, AWSVirtualPrivateGateway)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `AWSDirectConnect`. If the actual instance is not `AWSDirectConnect`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `AWSDirectConnect`
     * @throws ClassCastException if the instance is not `AWSDirectConnect`
     */
    public AWSDirectConnect getAWSDirectConnect() throws ClassCastException {
        return (AWSDirectConnect)super.getActualInstance();
    }

    /**
     * Get the actual instance of `AWSPermission`. If the actual instance is not `AWSPermission`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `AWSPermission`
     * @throws ClassCastException if the instance is not `AWSPermission`
     */
    public AWSPermission getAWSPermission() throws ClassCastException {
        return (AWSPermission)super.getActualInstance();
    }

    /**
     * Get the actual instance of `AWSVirtualPrivateGateway`. If the actual instance is not `AWSVirtualPrivateGateway`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `AWSVirtualPrivateGateway`
     * @throws ClassCastException if the instance is not `AWSVirtualPrivateGateway`
     */
    public AWSVirtualPrivateGateway getAWSVirtualPrivateGateway() throws ClassCastException {
        return (AWSVirtualPrivateGateway)super.getActualInstance();
    }


 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AWSProviderResource
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
    // validate oneOf schemas one by one
    int validCount = 0;
    ArrayList<String> errorMessages = new ArrayList<>();
    // validate the json string with AWSDirectConnect
    try {
      AWSDirectConnect.validateJsonObject(jsonObj);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for AWSDirectConnect failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with AWSPermission
    try {
      AWSPermission.validateJsonObject(jsonObj);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for AWSPermission failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with AWSVirtualPrivateGateway
    try {
      AWSVirtualPrivateGateway.validateJsonObject(jsonObj);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for AWSVirtualPrivateGateway failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    if (validCount != 1) {
      throw new IOException(String.format("The JSON string is invalid for AWSProviderResource with oneOf schemas: AWSDirectConnect, AWSPermission, AWSVirtualPrivateGateway. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonObj.toString()));
    }
  }

 /**
  * Create an instance of AWSProviderResource given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AWSProviderResource
  * @throws IOException if the JSON string is invalid with respect to AWSProviderResource
  */
  public static AWSProviderResource fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AWSProviderResource.class);
  }

 /**
  * Convert an instance of AWSProviderResource to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

