/*
 * Equinix Fabric API v4
 *
 * Contact: api-support@equinix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.fabric.v4.model;

import com.fasterxml.jackson.annotation.*;

import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * Fabric Cloud Router object
 */
@JsonPropertyOrder({
  CloudRouter.JSON_PROPERTY_HREF,
  CloudRouter.JSON_PROPERTY_UUID,
  CloudRouter.JSON_PROPERTY_NAME,
  CloudRouter.JSON_PROPERTY_STATE,
  CloudRouter.JSON_PROPERTY_EQUINIX_ASN,
  CloudRouter.JSON_PROPERTY_BGP_IPV4_ROUTES_COUNT,
  CloudRouter.JSON_PROPERTY_BGP_IPV6_ROUTES_COUNT,
  CloudRouter.JSON_PROPERTY_CONNECTIONS_COUNT,
  CloudRouter.JSON_PROPERTY_DISTINCT_IPV4_PREFIXES_COUNT,
  CloudRouter.JSON_PROPERTY_DISTINCT_IPV6_PREFIXES_COUNT,
  CloudRouter.JSON_PROPERTY_CHANGE_LOG,
  CloudRouter.JSON_PROPERTY_CHANGE,
  CloudRouter.JSON_PROPERTY_TYPE,
  CloudRouter.JSON_PROPERTY_LOCATION,
  CloudRouter.JSON_PROPERTY_PACKAGE,
  CloudRouter.JSON_PROPERTY_ORDER,
  CloudRouter.JSON_PROPERTY_PROJECT,
  CloudRouter.JSON_PROPERTY_ACCOUNT,
  CloudRouter.JSON_PROPERTY_NOTIFICATIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CloudRouter {
  public static final String JSON_PROPERTY_HREF = "href";
  private URI href;

  public static final String JSON_PROPERTY_UUID = "uuid";
  private UUID uuid;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_STATE = "state";
  private CloudRouterAccessPointState state;

  public static final String JSON_PROPERTY_EQUINIX_ASN = "equinixAsn";
  private Long equinixAsn;

  public static final String JSON_PROPERTY_BGP_IPV4_ROUTES_COUNT = "bgpIpv4RoutesCount";
  private Integer bgpIpv4RoutesCount;

  public static final String JSON_PROPERTY_BGP_IPV6_ROUTES_COUNT = "bgpIpv6RoutesCount";
  private Integer bgpIpv6RoutesCount;

  public static final String JSON_PROPERTY_CONNECTIONS_COUNT = "connectionsCount";
  private Integer connectionsCount;

  public static final String JSON_PROPERTY_DISTINCT_IPV4_PREFIXES_COUNT = "distinctIpv4PrefixesCount";
  private Integer distinctIpv4PrefixesCount;

  public static final String JSON_PROPERTY_DISTINCT_IPV6_PREFIXES_COUNT = "distinctIpv6PrefixesCount";
  private Integer distinctIpv6PrefixesCount;

  public static final String JSON_PROPERTY_CHANGE_LOG = "changeLog";
  private Changelog changeLog;

  public static final String JSON_PROPERTY_CHANGE = "change";
  private CloudRouterChange change;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    XF_ROUTER("XF_ROUTER");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public static final String JSON_PROPERTY_LOCATION = "location";
  private SimplifiedLocationWithoutIBX location;

  public static final String JSON_PROPERTY_PACKAGE = "package";
  private CloudRouterPostRequestPackage _package;

  public static final String JSON_PROPERTY_ORDER = "order";
  private Order order;

  public static final String JSON_PROPERTY_PROJECT = "project";
  private Project project;

  public static final String JSON_PROPERTY_ACCOUNT = "account";
  private SimplifiedAccount account;

  public static final String JSON_PROPERTY_NOTIFICATIONS = "notifications";
  private List<SimplifiedNotification> notifications = new ArrayList<>();

  public CloudRouter() {
  }

  @JsonCreator
  public CloudRouter(
    @JsonProperty(JSON_PROPERTY_HREF) URI href
  ) {
    this();
    this.href = href;
  }

   /**
   * Cloud Routers URI
   * @return href
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getHref() {
    return href;
  }




  public CloudRouter uuid(UUID uuid) {
    
    this.uuid = uuid;
    return this;
  }

   /**
   * Equinix-assigned access point identifier
   * @return uuid
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getUuid() {
    return uuid;
  }


  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }


  public CloudRouter name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Customer-provided Cloud Router name
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public CloudRouter state(CloudRouterAccessPointState state) {
    
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CloudRouterAccessPointState getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(CloudRouterAccessPointState state) {
    this.state = state;
  }


  public CloudRouter equinixAsn(Long equinixAsn) {
    
    this.equinixAsn = equinixAsn;
    return this;
  }

   /**
   * Equinix ASN
   * @return equinixAsn
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EQUINIX_ASN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getEquinixAsn() {
    return equinixAsn;
  }


  @JsonProperty(JSON_PROPERTY_EQUINIX_ASN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEquinixAsn(Long equinixAsn) {
    this.equinixAsn = equinixAsn;
  }


  public CloudRouter bgpIpv4RoutesCount(Integer bgpIpv4RoutesCount) {
    
    this.bgpIpv4RoutesCount = bgpIpv4RoutesCount;
    return this;
  }

   /**
   * Access point used and maximum number of IPv4 BGP routes
   * minimum: 0
   * @return bgpIpv4RoutesCount
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BGP_IPV4_ROUTES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getBgpIpv4RoutesCount() {
    return bgpIpv4RoutesCount;
  }


  @JsonProperty(JSON_PROPERTY_BGP_IPV4_ROUTES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBgpIpv4RoutesCount(Integer bgpIpv4RoutesCount) {
    this.bgpIpv4RoutesCount = bgpIpv4RoutesCount;
  }


  public CloudRouter bgpIpv6RoutesCount(Integer bgpIpv6RoutesCount) {
    
    this.bgpIpv6RoutesCount = bgpIpv6RoutesCount;
    return this;
  }

   /**
   * Access point used and maximum number of IPv6 BGP routes
   * minimum: 0
   * @return bgpIpv6RoutesCount
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BGP_IPV6_ROUTES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getBgpIpv6RoutesCount() {
    return bgpIpv6RoutesCount;
  }


  @JsonProperty(JSON_PROPERTY_BGP_IPV6_ROUTES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBgpIpv6RoutesCount(Integer bgpIpv6RoutesCount) {
    this.bgpIpv6RoutesCount = bgpIpv6RoutesCount;
  }


  public CloudRouter connectionsCount(Integer connectionsCount) {
    
    this.connectionsCount = connectionsCount;
    return this;
  }

   /**
   * Number of connections associated with this Access point
   * minimum: 0
   * @return connectionsCount
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONNECTIONS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getConnectionsCount() {
    return connectionsCount;
  }


  @JsonProperty(JSON_PROPERTY_CONNECTIONS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConnectionsCount(Integer connectionsCount) {
    this.connectionsCount = connectionsCount;
  }


  public CloudRouter distinctIpv4PrefixesCount(Integer distinctIpv4PrefixesCount) {
    
    this.distinctIpv4PrefixesCount = distinctIpv4PrefixesCount;
    return this;
  }

   /**
   * Number of distinct ipv4 routes
   * minimum: 0
   * @return distinctIpv4PrefixesCount
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISTINCT_IPV4_PREFIXES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDistinctIpv4PrefixesCount() {
    return distinctIpv4PrefixesCount;
  }


  @JsonProperty(JSON_PROPERTY_DISTINCT_IPV4_PREFIXES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDistinctIpv4PrefixesCount(Integer distinctIpv4PrefixesCount) {
    this.distinctIpv4PrefixesCount = distinctIpv4PrefixesCount;
  }


  public CloudRouter distinctIpv6PrefixesCount(Integer distinctIpv6PrefixesCount) {
    
    this.distinctIpv6PrefixesCount = distinctIpv6PrefixesCount;
    return this;
  }

   /**
   * Number of distinct ipv6 routes
   * minimum: 0
   * @return distinctIpv6PrefixesCount
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISTINCT_IPV6_PREFIXES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDistinctIpv6PrefixesCount() {
    return distinctIpv6PrefixesCount;
  }


  @JsonProperty(JSON_PROPERTY_DISTINCT_IPV6_PREFIXES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDistinctIpv6PrefixesCount(Integer distinctIpv6PrefixesCount) {
    this.distinctIpv6PrefixesCount = distinctIpv6PrefixesCount;
  }


  public CloudRouter changeLog(Changelog changeLog) {
    
    this.changeLog = changeLog;
    return this;
  }

   /**
   * Get changeLog
   * @return changeLog
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHANGE_LOG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Changelog getChangeLog() {
    return changeLog;
  }


  @JsonProperty(JSON_PROPERTY_CHANGE_LOG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChangeLog(Changelog changeLog) {
    this.changeLog = changeLog;
  }


  public CloudRouter change(CloudRouterChange change) {
    
    this.change = change;
    return this;
  }

   /**
   * Get change
   * @return change
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CloudRouterChange getChange() {
    return change;
  }


  @JsonProperty(JSON_PROPERTY_CHANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChange(CloudRouterChange change) {
    this.change = change;
  }


  public CloudRouter type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(TypeEnum type) {
    this.type = type;
  }


  public CloudRouter location(SimplifiedLocationWithoutIBX location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SimplifiedLocationWithoutIBX getLocation() {
    return location;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(SimplifiedLocationWithoutIBX location) {
    this.location = location;
  }


  public CloudRouter _package(CloudRouterPostRequestPackage _package) {
    
    this._package = _package;
    return this;
  }

   /**
   * Get _package
   * @return _package
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PACKAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CloudRouterPostRequestPackage getPackage() {
    return _package;
  }


  @JsonProperty(JSON_PROPERTY_PACKAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPackage(CloudRouterPostRequestPackage _package) {
    this._package = _package;
  }


  public CloudRouter order(Order order) {
    
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Order getOrder() {
    return order;
  }


  @JsonProperty(JSON_PROPERTY_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrder(Order order) {
    this.order = order;
  }


  public CloudRouter project(Project project) {
    
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Project getProject() {
    return project;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProject(Project project) {
    this.project = project;
  }


  public CloudRouter account(SimplifiedAccount account) {
    
    this.account = account;
    return this;
  }

   /**
   * Get account
   * @return account
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SimplifiedAccount getAccount() {
    return account;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccount(SimplifiedAccount account) {
    this.account = account;
  }


  public CloudRouter notifications(List<SimplifiedNotification> notifications) {
    
    this.notifications = notifications;
    return this;
  }

  public CloudRouter addNotificationsItem(SimplifiedNotification notificationsItem) {
    if (this.notifications == null) {
      this.notifications = new ArrayList<>();
    }
    this.notifications.add(notificationsItem);
    return this;
  }

   /**
   * Preferences for notifications on connection configuration or status changes
   * @return notifications
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOTIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SimplifiedNotification> getNotifications() {
    return notifications;
  }


  @JsonProperty(JSON_PROPERTY_NOTIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotifications(List<SimplifiedNotification> notifications) {
    this.notifications = notifications;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudRouter cloudRouter = (CloudRouter) o;
    return Objects.equals(this.href, cloudRouter.href) &&
        Objects.equals(this.uuid, cloudRouter.uuid) &&
        Objects.equals(this.name, cloudRouter.name) &&
        Objects.equals(this.state, cloudRouter.state) &&
        Objects.equals(this.equinixAsn, cloudRouter.equinixAsn) &&
        Objects.equals(this.bgpIpv4RoutesCount, cloudRouter.bgpIpv4RoutesCount) &&
        Objects.equals(this.bgpIpv6RoutesCount, cloudRouter.bgpIpv6RoutesCount) &&
        Objects.equals(this.connectionsCount, cloudRouter.connectionsCount) &&
        Objects.equals(this.distinctIpv4PrefixesCount, cloudRouter.distinctIpv4PrefixesCount) &&
        Objects.equals(this.distinctIpv6PrefixesCount, cloudRouter.distinctIpv6PrefixesCount) &&
        Objects.equals(this.changeLog, cloudRouter.changeLog) &&
        Objects.equals(this.change, cloudRouter.change) &&
        Objects.equals(this.type, cloudRouter.type) &&
        Objects.equals(this.location, cloudRouter.location) &&
        Objects.equals(this._package, cloudRouter._package) &&
        Objects.equals(this.order, cloudRouter.order) &&
        Objects.equals(this.project, cloudRouter.project) &&
        Objects.equals(this.account, cloudRouter.account) &&
        Objects.equals(this.notifications, cloudRouter.notifications);
  }

  @Override
  public int hashCode() {
    return Objects.hash(href, uuid, name, state, equinixAsn, bgpIpv4RoutesCount, bgpIpv6RoutesCount, connectionsCount, distinctIpv4PrefixesCount, distinctIpv6PrefixesCount, changeLog, change, type, location, _package, order, project, account, notifications);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudRouter {\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    equinixAsn: ").append(toIndentedString(equinixAsn)).append("\n");
    sb.append("    bgpIpv4RoutesCount: ").append(toIndentedString(bgpIpv4RoutesCount)).append("\n");
    sb.append("    bgpIpv6RoutesCount: ").append(toIndentedString(bgpIpv6RoutesCount)).append("\n");
    sb.append("    connectionsCount: ").append(toIndentedString(connectionsCount)).append("\n");
    sb.append("    distinctIpv4PrefixesCount: ").append(toIndentedString(distinctIpv4PrefixesCount)).append("\n");
    sb.append("    distinctIpv6PrefixesCount: ").append(toIndentedString(distinctIpv6PrefixesCount)).append("\n");
    sb.append("    changeLog: ").append(toIndentedString(changeLog)).append("\n");
    sb.append("    change: ").append(toIndentedString(change)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    _package: ").append(toIndentedString(_package)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    notifications: ").append(toIndentedString(notifications)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

