/*
 * Equinix Fabric API v4
 *
 * Contact: api-support@equinix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.fabric.v4.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Network status
 */
@JsonAdapter(LinkProtocolState.Adapter.class)
public enum LinkProtocolState {
  
  RESERVED("RESERVED"),
  
  RELEASED("RELEASED");

  private String value;

  LinkProtocolState(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static LinkProtocolState fromValue(String value) {
    for (LinkProtocolState b : LinkProtocolState.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<LinkProtocolState> {
    @Override
    public void write(final JsonWriter jsonWriter, final LinkProtocolState enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public LinkProtocolState read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return LinkProtocolState.fromValue(value);
    }
  }
}

