/*
 * Equinix Fabric API v4
 *
 * Contact: api-support@equinix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.fabric.v4.model;

import java.util.Objects;
import java.util.Arrays;
import com.equinix.openapi.fabric.v4.model.PortOrderPurchaseOrder;
import com.equinix.openapi.fabric.v4.model.PortOrderSignature;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PortOrder
 */
@JsonPropertyOrder({
  PortOrder.JSON_PROPERTY_PURCHASE_ORDER,
  PortOrder.JSON_PROPERTY_ORDER_ID,
  PortOrder.JSON_PROPERTY_ORDER_NUMBER,
  PortOrder.JSON_PROPERTY_UUID,
  PortOrder.JSON_PROPERTY_SIGNATURE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PortOrder {
  public static final String JSON_PROPERTY_PURCHASE_ORDER = "purchaseOrder";
  private PortOrderPurchaseOrder purchaseOrder;

  public static final String JSON_PROPERTY_ORDER_ID = "orderId";
  private String orderId;

  public static final String JSON_PROPERTY_ORDER_NUMBER = "orderNumber";
  private String orderNumber;

  public static final String JSON_PROPERTY_UUID = "uuid";
  private UUID uuid;

  public static final String JSON_PROPERTY_SIGNATURE = "signature";
  private PortOrderSignature signature;

  public PortOrder() {
  }

  public PortOrder purchaseOrder(PortOrderPurchaseOrder purchaseOrder) {
    
    this.purchaseOrder = purchaseOrder;
    return this;
  }

   /**
   * Get purchaseOrder
   * @return purchaseOrder
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PURCHASE_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PortOrderPurchaseOrder getPurchaseOrder() {
    return purchaseOrder;
  }


  @JsonProperty(JSON_PROPERTY_PURCHASE_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPurchaseOrder(PortOrderPurchaseOrder purchaseOrder) {
    this.purchaseOrder = purchaseOrder;
  }


  public PortOrder orderId(String orderId) {
    
    this.orderId = orderId;
    return this;
  }

   /**
   * Order Identification
   * @return orderId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrderId() {
    return orderId;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }


  public PortOrder orderNumber(String orderNumber) {
    
    this.orderNumber = orderNumber;
    return this;
  }

   /**
   * Order Reference Number
   * @return orderNumber
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrderNumber() {
    return orderNumber;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderNumber(String orderNumber) {
    this.orderNumber = orderNumber;
  }


  public PortOrder uuid(UUID uuid) {
    
    this.uuid = uuid;
    return this;
  }

   /**
   * Equinix-assigned order identifier
   * @return uuid
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getUuid() {
    return uuid;
  }


  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }


  public PortOrder signature(PortOrderSignature signature) {
    
    this.signature = signature;
    return this;
  }

   /**
   * Get signature
   * @return signature
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PortOrderSignature getSignature() {
    return signature;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignature(PortOrderSignature signature) {
    this.signature = signature;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PortOrder portOrder = (PortOrder) o;
    return Objects.equals(this.purchaseOrder, portOrder.purchaseOrder) &&
        Objects.equals(this.orderId, portOrder.orderId) &&
        Objects.equals(this.orderNumber, portOrder.orderNumber) &&
        Objects.equals(this.uuid, portOrder.uuid) &&
        Objects.equals(this.signature, portOrder.signature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(purchaseOrder, orderId, orderNumber, uuid, signature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PortOrder {\n");
    sb.append("    purchaseOrder: ").append(toIndentedString(purchaseOrder)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    orderNumber: ").append(toIndentedString(orderNumber)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

