/*
 * Equinix Fabric API v4
 *
 * Contact: api-support@equinix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.fabric.v4.model;

import java.util.Objects;
import java.util.Arrays;
import com.equinix.openapi.fabric.v4.model.Changelog;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EPT Service Package Information
 */
@JsonPropertyOrder({
  PrecisionTimePackageResponse.JSON_PROPERTY_HREF,
  PrecisionTimePackageResponse.JSON_PROPERTY_CODE,
  PrecisionTimePackageResponse.JSON_PROPERTY_TYPE,
  PrecisionTimePackageResponse.JSON_PROPERTY_BANDWIDTH,
  PrecisionTimePackageResponse.JSON_PROPERTY_CLIENTS_PER_SECOND_MAX,
  PrecisionTimePackageResponse.JSON_PROPERTY_REDUNDANCY_SUPPORTED,
  PrecisionTimePackageResponse.JSON_PROPERTY_MULTI_SUBNET_SUPPORTED,
  PrecisionTimePackageResponse.JSON_PROPERTY_ACCURACY_UNIT,
  PrecisionTimePackageResponse.JSON_PROPERTY_ACCURACY_SLA,
  PrecisionTimePackageResponse.JSON_PROPERTY_ACCURACY_AVG_MIN,
  PrecisionTimePackageResponse.JSON_PROPERTY_ACCURACY_AVG_MAX,
  PrecisionTimePackageResponse.JSON_PROPERTY_CHANGELOG
})
@JsonTypeName("precisionTimePackageResponse")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PrecisionTimePackageResponse {
  public static final String JSON_PROPERTY_HREF = "href";
  private URI href;

  /**
   * Gets or Sets code
   */
  public enum CodeEnum {
    NTP_STANDARD("NTP_STANDARD"),
    
    NTP_ENTERPRISE("NTP_ENTERPRISE"),
    
    PTP_STANDARD("PTP_STANDARD"),
    
    PTP_ENTERPRISE("PTP_ENTERPRISE");

    private String value;

    CodeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CodeEnum fromValue(String value) {
      for (CodeEnum b : CodeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CODE = "code";
  private CodeEnum code;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    TIME_SERVICE_PACKAGE("TIME_SERVICE_PACKAGE");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public static final String JSON_PROPERTY_BANDWIDTH = "bandwidth";
  private Integer bandwidth;

  public static final String JSON_PROPERTY_CLIENTS_PER_SECOND_MAX = "clientsPerSecondMax";
  private Integer clientsPerSecondMax;

  public static final String JSON_PROPERTY_REDUNDANCY_SUPPORTED = "redundancySupported";
  private Boolean redundancySupported;

  public static final String JSON_PROPERTY_MULTI_SUBNET_SUPPORTED = "multiSubnetSupported";
  private Boolean multiSubnetSupported;

  public static final String JSON_PROPERTY_ACCURACY_UNIT = "accuracyUnit";
  private String accuracyUnit;

  public static final String JSON_PROPERTY_ACCURACY_SLA = "accuracySla";
  private Integer accuracySla;

  public static final String JSON_PROPERTY_ACCURACY_AVG_MIN = "accuracyAvgMin";
  private Integer accuracyAvgMin;

  public static final String JSON_PROPERTY_ACCURACY_AVG_MAX = "accuracyAvgMax";
  private Integer accuracyAvgMax;

  public static final String JSON_PROPERTY_CHANGELOG = "changelog";
  private Changelog changelog;

  public PrecisionTimePackageResponse() {
  }

  public PrecisionTimePackageResponse href(URI href) {
    
    this.href = href;
    return this;
  }

   /**
   * Get href
   * @return href
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getHref() {
    return href;
  }


  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHref(URI href) {
    this.href = href;
  }


  public PrecisionTimePackageResponse code(CodeEnum code) {
    
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CodeEnum getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(CodeEnum code) {
    this.code = code;
  }


  public PrecisionTimePackageResponse type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(TypeEnum type) {
    this.type = type;
  }


  public PrecisionTimePackageResponse bandwidth(Integer bandwidth) {
    
    this.bandwidth = bandwidth;
    return this;
  }

   /**
   * Get bandwidth
   * @return bandwidth
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BANDWIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getBandwidth() {
    return bandwidth;
  }


  @JsonProperty(JSON_PROPERTY_BANDWIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBandwidth(Integer bandwidth) {
    this.bandwidth = bandwidth;
  }


  public PrecisionTimePackageResponse clientsPerSecondMax(Integer clientsPerSecondMax) {
    
    this.clientsPerSecondMax = clientsPerSecondMax;
    return this;
  }

   /**
   * Get clientsPerSecondMax
   * @return clientsPerSecondMax
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLIENTS_PER_SECOND_MAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getClientsPerSecondMax() {
    return clientsPerSecondMax;
  }


  @JsonProperty(JSON_PROPERTY_CLIENTS_PER_SECOND_MAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientsPerSecondMax(Integer clientsPerSecondMax) {
    this.clientsPerSecondMax = clientsPerSecondMax;
  }


  public PrecisionTimePackageResponse redundancySupported(Boolean redundancySupported) {
    
    this.redundancySupported = redundancySupported;
    return this;
  }

   /**
   * Get redundancySupported
   * @return redundancySupported
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REDUNDANCY_SUPPORTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRedundancySupported() {
    return redundancySupported;
  }


  @JsonProperty(JSON_PROPERTY_REDUNDANCY_SUPPORTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRedundancySupported(Boolean redundancySupported) {
    this.redundancySupported = redundancySupported;
  }


  public PrecisionTimePackageResponse multiSubnetSupported(Boolean multiSubnetSupported) {
    
    this.multiSubnetSupported = multiSubnetSupported;
    return this;
  }

   /**
   * Get multiSubnetSupported
   * @return multiSubnetSupported
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MULTI_SUBNET_SUPPORTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMultiSubnetSupported() {
    return multiSubnetSupported;
  }


  @JsonProperty(JSON_PROPERTY_MULTI_SUBNET_SUPPORTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMultiSubnetSupported(Boolean multiSubnetSupported) {
    this.multiSubnetSupported = multiSubnetSupported;
  }


  public PrecisionTimePackageResponse accuracyUnit(String accuracyUnit) {
    
    this.accuracyUnit = accuracyUnit;
    return this;
  }

   /**
   * Get accuracyUnit
   * @return accuracyUnit
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCURACY_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccuracyUnit() {
    return accuracyUnit;
  }


  @JsonProperty(JSON_PROPERTY_ACCURACY_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccuracyUnit(String accuracyUnit) {
    this.accuracyUnit = accuracyUnit;
  }


  public PrecisionTimePackageResponse accuracySla(Integer accuracySla) {
    
    this.accuracySla = accuracySla;
    return this;
  }

   /**
   * Get accuracySla
   * @return accuracySla
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCURACY_SLA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAccuracySla() {
    return accuracySla;
  }


  @JsonProperty(JSON_PROPERTY_ACCURACY_SLA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccuracySla(Integer accuracySla) {
    this.accuracySla = accuracySla;
  }


  public PrecisionTimePackageResponse accuracyAvgMin(Integer accuracyAvgMin) {
    
    this.accuracyAvgMin = accuracyAvgMin;
    return this;
  }

   /**
   * Get accuracyAvgMin
   * @return accuracyAvgMin
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCURACY_AVG_MIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAccuracyAvgMin() {
    return accuracyAvgMin;
  }


  @JsonProperty(JSON_PROPERTY_ACCURACY_AVG_MIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccuracyAvgMin(Integer accuracyAvgMin) {
    this.accuracyAvgMin = accuracyAvgMin;
  }


  public PrecisionTimePackageResponse accuracyAvgMax(Integer accuracyAvgMax) {
    
    this.accuracyAvgMax = accuracyAvgMax;
    return this;
  }

   /**
   * Get accuracyAvgMax
   * @return accuracyAvgMax
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCURACY_AVG_MAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAccuracyAvgMax() {
    return accuracyAvgMax;
  }


  @JsonProperty(JSON_PROPERTY_ACCURACY_AVG_MAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccuracyAvgMax(Integer accuracyAvgMax) {
    this.accuracyAvgMax = accuracyAvgMax;
  }


  public PrecisionTimePackageResponse changelog(Changelog changelog) {
    
    this.changelog = changelog;
    return this;
  }

   /**
   * Get changelog
   * @return changelog
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHANGELOG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Changelog getChangelog() {
    return changelog;
  }


  @JsonProperty(JSON_PROPERTY_CHANGELOG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChangelog(Changelog changelog) {
    this.changelog = changelog;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrecisionTimePackageResponse precisionTimePackageResponse = (PrecisionTimePackageResponse) o;
    return Objects.equals(this.href, precisionTimePackageResponse.href) &&
        Objects.equals(this.code, precisionTimePackageResponse.code) &&
        Objects.equals(this.type, precisionTimePackageResponse.type) &&
        Objects.equals(this.bandwidth, precisionTimePackageResponse.bandwidth) &&
        Objects.equals(this.clientsPerSecondMax, precisionTimePackageResponse.clientsPerSecondMax) &&
        Objects.equals(this.redundancySupported, precisionTimePackageResponse.redundancySupported) &&
        Objects.equals(this.multiSubnetSupported, precisionTimePackageResponse.multiSubnetSupported) &&
        Objects.equals(this.accuracyUnit, precisionTimePackageResponse.accuracyUnit) &&
        Objects.equals(this.accuracySla, precisionTimePackageResponse.accuracySla) &&
        Objects.equals(this.accuracyAvgMin, precisionTimePackageResponse.accuracyAvgMin) &&
        Objects.equals(this.accuracyAvgMax, precisionTimePackageResponse.accuracyAvgMax) &&
        Objects.equals(this.changelog, precisionTimePackageResponse.changelog);
  }

  @Override
  public int hashCode() {
    return Objects.hash(href, code, type, bandwidth, clientsPerSecondMax, redundancySupported, multiSubnetSupported, accuracyUnit, accuracySla, accuracyAvgMin, accuracyAvgMax, changelog);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrecisionTimePackageResponse {\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    bandwidth: ").append(toIndentedString(bandwidth)).append("\n");
    sb.append("    clientsPerSecondMax: ").append(toIndentedString(clientsPerSecondMax)).append("\n");
    sb.append("    redundancySupported: ").append(toIndentedString(redundancySupported)).append("\n");
    sb.append("    multiSubnetSupported: ").append(toIndentedString(multiSubnetSupported)).append("\n");
    sb.append("    accuracyUnit: ").append(toIndentedString(accuracyUnit)).append("\n");
    sb.append("    accuracySla: ").append(toIndentedString(accuracySla)).append("\n");
    sb.append("    accuracyAvgMin: ").append(toIndentedString(accuracyAvgMin)).append("\n");
    sb.append("    accuracyAvgMax: ").append(toIndentedString(accuracyAvgMax)).append("\n");
    sb.append("    changelog: ").append(toIndentedString(changelog)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

