/*
 * Equinix Fabric API v4
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br> </br> <b>Integrations (SDKs, Tools) links:</b></br> <a href=\"https://deploy.equinix.com/labs/fabric-java\\\">Fabric Java SDK</a> </br> <a href=\"https://deploy.equinix.com/labs/equinix-sdk-go\\\">Fabric Go SDK</a> </br> <a href=\"https://deploy.equinix.com/labs/terraform-provider-equinix\\\">Equinix Terraform Provider</a> </br> <a href=\"https://deploy.equinix.com/labs/terraform-equinix-fabric\\\">Fabric Terraform Modules</a> </br> <a href=\"https://deploy.equinix.com/labs/pulumi-provider-equinix/\">Equinix Pulumi Provider</a> </br>
 *
 * Contact: api-support@equinix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.fabric.v4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Connection provider readiness status
 */
@JsonAdapter(ProviderStatus.Adapter.class)
public enum ProviderStatus {
  
  AVAILABLE("AVAILABLE"),
  
  DEPROVISIONED("DEPROVISIONED"),
  
  DEPROVISIONING("DEPROVISIONING"),
  
  FAILED("FAILED"),
  
  NOT_AVAILABLE("NOT_AVAILABLE"),
  
  PENDING_APPROVAL("PENDING_APPROVAL"),
  
  PENDING_CONFIGURATION("PENDING_CONFIGURATION"),
  
  PROVISIONED("PROVISIONED"),
  
  PROVISIONING("PROVISIONING"),
  
  REJECTED("REJECTED"),
  
  PENDING_BGP("PENDING_BGP"),
  
  OUT_OF_BANDWIDTH("OUT_OF_BANDWIDTH"),
  
  DELETED("DELETED"),
  
  ERROR("ERROR"),
  
  ERRORED("ERRORED"),
  
  NOTPROVISIONED("NOTPROVISIONED"),
  
  NOT_PROVISIONED("NOT_PROVISIONED"),
  
  ORDERING("ORDERING"),
  
  DELETING("DELETING"),
  
  PENDING_DELETE("PENDING DELETE"),
  
  N_A("N/A");

  private String value;

  ProviderStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ProviderStatus fromValue(String value) {
    for (ProviderStatus b : ProviderStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ProviderStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final ProviderStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ProviderStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ProviderStatus.fromValue(value);
    }
  }
}

