/*
 * Equinix Fabric API v4
 *
 * Contact: api-support@equinix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.fabric.v4.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Route Filter status
 */
public enum RouteFilterState {
  
  PROVISIONING("PROVISIONING"),
  
  REPROVISIONING("REPROVISIONING"),
  
  DEPROVISIONING("DEPROVISIONING"),
  
  PROVISIONED("PROVISIONED"),
  
  DEPROVISIONED("DEPROVISIONED"),
  
  NOT_PROVISIONED("NOT_PROVISIONED"),
  
  NOT_DEPROVISIONED("NOT_DEPROVISIONED");

  private String value;

  RouteFilterState(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static RouteFilterState fromValue(String value) {
    for (RouteFilterState b : RouteFilterState.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

