/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.fabric.v4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Route Filter Rule status
 */
@JsonAdapter(RouteFilterRuleState.Adapter.class)
public enum RouteFilterRuleState {
  
  PROVISIONING("PROVISIONING"),
  
  REPROVISIONING("REPROVISIONING"),
  
  DEPROVISIONING("DEPROVISIONING"),
  
  PROVISIONED("PROVISIONED"),
  
  DEPROVISIONED("DEPROVISIONED"),
  
  NOT_PROVISIONED("NOT_PROVISIONED"),
  
  NOT_DEPROVISIONED("NOT_DEPROVISIONED");

  private String value;

  RouteFilterRuleState(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static RouteFilterRuleState fromValue(String value) {
    for (RouteFilterRuleState b : RouteFilterRuleState.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<RouteFilterRuleState> {
    @Override
    public void write(final JsonWriter jsonWriter, final RouteFilterRuleState enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public RouteFilterRuleState read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return RouteFilterRuleState.fromValue(value);
    }
  }
}

