/*
 * Equinix Fabric API v4
 *
 * Contact: api-support@equinix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.fabric.v4.model;

import com.fasterxml.jackson.annotation.*;

import java.util.Objects;

/**
 * RoutingProtocolBase
 */
@JsonPropertyOrder({
  RoutingProtocolBase.JSON_PROPERTY_TYPE,
  RoutingProtocolBase.JSON_PROPERTY_NAME,
  RoutingProtocolBase.JSON_PROPERTY_BGP_IPV4,
  RoutingProtocolBase.JSON_PROPERTY_BGP_IPV6,
  RoutingProtocolBase.JSON_PROPERTY_CUSTOMER_ASN,
  RoutingProtocolBase.JSON_PROPERTY_EQUINIX_ASN,
  RoutingProtocolBase.JSON_PROPERTY_BGP_AUTH_KEY,
  RoutingProtocolBase.JSON_PROPERTY_BFD,
  RoutingProtocolBase.JSON_PROPERTY_DIRECT_IPV4,
  RoutingProtocolBase.JSON_PROPERTY_DIRECT_IPV6
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RoutingProtocolBase {
  /**
   * Routing protocol type
   */
  public enum TypeEnum {
    BGP("BGP"),
    
    DIRECT("DIRECT");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_BGP_IPV4 = "bgpIpv4";
  private BGPConnectionIpv4 bgpIpv4;

  public static final String JSON_PROPERTY_BGP_IPV6 = "bgpIpv6";
  private BGPConnectionIpv6 bgpIpv6;

  public static final String JSON_PROPERTY_CUSTOMER_ASN = "customerAsn";
  private Long customerAsn;

  public static final String JSON_PROPERTY_EQUINIX_ASN = "equinixAsn";
  private Long equinixAsn;

  public static final String JSON_PROPERTY_BGP_AUTH_KEY = "bgpAuthKey";
  private String bgpAuthKey;

  public static final String JSON_PROPERTY_BFD = "bfd";
  private RoutingProtocolBFD bfd;

  public static final String JSON_PROPERTY_DIRECT_IPV4 = "directIpv4";
  private DirectConnectionIpv4 directIpv4;

  public static final String JSON_PROPERTY_DIRECT_IPV6 = "directIpv6";
  private DirectConnectionIpv6 directIpv6;

  public RoutingProtocolBase() {
  }

  public RoutingProtocolBase type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Routing protocol type
   * @return type
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(TypeEnum type) {
    this.type = type;
  }


  public RoutingProtocolBase name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public RoutingProtocolBase bgpIpv4(BGPConnectionIpv4 bgpIpv4) {
    
    this.bgpIpv4 = bgpIpv4;
    return this;
  }

   /**
   * Get bgpIpv4
   * @return bgpIpv4
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BGP_IPV4)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BGPConnectionIpv4 getBgpIpv4() {
    return bgpIpv4;
  }


  @JsonProperty(JSON_PROPERTY_BGP_IPV4)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBgpIpv4(BGPConnectionIpv4 bgpIpv4) {
    this.bgpIpv4 = bgpIpv4;
  }


  public RoutingProtocolBase bgpIpv6(BGPConnectionIpv6 bgpIpv6) {
    
    this.bgpIpv6 = bgpIpv6;
    return this;
  }

   /**
   * Get bgpIpv6
   * @return bgpIpv6
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BGP_IPV6)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BGPConnectionIpv6 getBgpIpv6() {
    return bgpIpv6;
  }


  @JsonProperty(JSON_PROPERTY_BGP_IPV6)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBgpIpv6(BGPConnectionIpv6 bgpIpv6) {
    this.bgpIpv6 = bgpIpv6;
  }


  public RoutingProtocolBase customerAsn(Long customerAsn) {
    
    this.customerAsn = customerAsn;
    return this;
  }

   /**
   * Customer asn
   * @return customerAsn
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOMER_ASN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCustomerAsn() {
    return customerAsn;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMER_ASN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomerAsn(Long customerAsn) {
    this.customerAsn = customerAsn;
  }


  public RoutingProtocolBase equinixAsn(Long equinixAsn) {
    
    this.equinixAsn = equinixAsn;
    return this;
  }

   /**
   * Equinix asn
   * @return equinixAsn
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EQUINIX_ASN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getEquinixAsn() {
    return equinixAsn;
  }


  @JsonProperty(JSON_PROPERTY_EQUINIX_ASN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEquinixAsn(Long equinixAsn) {
    this.equinixAsn = equinixAsn;
  }


  public RoutingProtocolBase bgpAuthKey(String bgpAuthKey) {
    
    this.bgpAuthKey = bgpAuthKey;
    return this;
  }

   /**
   * BGP authorization key
   * @return bgpAuthKey
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BGP_AUTH_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBgpAuthKey() {
    return bgpAuthKey;
  }


  @JsonProperty(JSON_PROPERTY_BGP_AUTH_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBgpAuthKey(String bgpAuthKey) {
    this.bgpAuthKey = bgpAuthKey;
  }


  public RoutingProtocolBase bfd(RoutingProtocolBFD bfd) {
    
    this.bfd = bfd;
    return this;
  }

   /**
   * Get bfd
   * @return bfd
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BFD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RoutingProtocolBFD getBfd() {
    return bfd;
  }


  @JsonProperty(JSON_PROPERTY_BFD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBfd(RoutingProtocolBFD bfd) {
    this.bfd = bfd;
  }


  public RoutingProtocolBase directIpv4(DirectConnectionIpv4 directIpv4) {
    
    this.directIpv4 = directIpv4;
    return this;
  }

   /**
   * Get directIpv4
   * @return directIpv4
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIRECT_IPV4)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DirectConnectionIpv4 getDirectIpv4() {
    return directIpv4;
  }


  @JsonProperty(JSON_PROPERTY_DIRECT_IPV4)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDirectIpv4(DirectConnectionIpv4 directIpv4) {
    this.directIpv4 = directIpv4;
  }


  public RoutingProtocolBase directIpv6(DirectConnectionIpv6 directIpv6) {
    
    this.directIpv6 = directIpv6;
    return this;
  }

   /**
   * Get directIpv6
   * @return directIpv6
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIRECT_IPV6)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DirectConnectionIpv6 getDirectIpv6() {
    return directIpv6;
  }


  @JsonProperty(JSON_PROPERTY_DIRECT_IPV6)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDirectIpv6(DirectConnectionIpv6 directIpv6) {
    this.directIpv6 = directIpv6;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoutingProtocolBase routingProtocolBase = (RoutingProtocolBase) o;
    return Objects.equals(this.type, routingProtocolBase.type) &&
        Objects.equals(this.name, routingProtocolBase.name) &&
        Objects.equals(this.bgpIpv4, routingProtocolBase.bgpIpv4) &&
        Objects.equals(this.bgpIpv6, routingProtocolBase.bgpIpv6) &&
        Objects.equals(this.customerAsn, routingProtocolBase.customerAsn) &&
        Objects.equals(this.equinixAsn, routingProtocolBase.equinixAsn) &&
        Objects.equals(this.bgpAuthKey, routingProtocolBase.bgpAuthKey) &&
        Objects.equals(this.bfd, routingProtocolBase.bfd) &&
        Objects.equals(this.directIpv4, routingProtocolBase.directIpv4) &&
        Objects.equals(this.directIpv6, routingProtocolBase.directIpv6);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, name, bgpIpv4, bgpIpv6, customerAsn, equinixAsn, bgpAuthKey, bfd, directIpv4, directIpv6);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoutingProtocolBase {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    bgpIpv4: ").append(toIndentedString(bgpIpv4)).append("\n");
    sb.append("    bgpIpv6: ").append(toIndentedString(bgpIpv6)).append("\n");
    sb.append("    customerAsn: ").append(toIndentedString(customerAsn)).append("\n");
    sb.append("    equinixAsn: ").append(toIndentedString(equinixAsn)).append("\n");
    sb.append("    bgpAuthKey: ").append(toIndentedString(bgpAuthKey)).append("\n");
    sb.append("    bfd: ").append(toIndentedString(bfd)).append("\n");
    sb.append("    directIpv4: ").append(toIndentedString(directIpv4)).append("\n");
    sb.append("    directIpv6: ").append(toIndentedString(directIpv6)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

