/*
 * Equinix Fabric API v4
 *
 * Contact: api-support@equinix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.fabric.v4.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServiceMetro
 */
@JsonPropertyOrder({
  ServiceMetro.JSON_PROPERTY_CODE,
  ServiceMetro.JSON_PROPERTY_NAME,
  ServiceMetro.JSON_PROPERTY_VC_BANDWIDTH_MAX,
  ServiceMetro.JSON_PROPERTY_IBXS,
  ServiceMetro.JSON_PROPERTY_IN_TRAIL,
  ServiceMetro.JSON_PROPERTY_DISPLAY_NAME,
  ServiceMetro.JSON_PROPERTY_SELLER_REGIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ServiceMetro {
  public static final String JSON_PROPERTY_CODE = "code";
  private String code;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_VC_BANDWIDTH_MAX = "vcBandwidthMax";
  private Integer vcBandwidthMax;

  public static final String JSON_PROPERTY_IBXS = "ibxs";
  private List<String> ibxs = new ArrayList<>();

  public static final String JSON_PROPERTY_IN_TRAIL = "inTrail";
  private Boolean inTrail;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  private String displayName;

  public static final String JSON_PROPERTY_SELLER_REGIONS = "sellerRegions";
  private Map<String, String> sellerRegions = new HashMap<>();

  public ServiceMetro() {
  }

  public ServiceMetro code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * metro code
   * @return code
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(String code) {
    this.code = code;
  }


  public ServiceMetro name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * metro name
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public ServiceMetro vcBandwidthMax(Integer vcBandwidthMax) {
    
    this.vcBandwidthMax = vcBandwidthMax;
    return this;
  }

   /**
   * max VC speed supported in Mbps
   * @return vcBandwidthMax
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VC_BANDWIDTH_MAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getVcBandwidthMax() {
    return vcBandwidthMax;
  }


  @JsonProperty(JSON_PROPERTY_VC_BANDWIDTH_MAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVcBandwidthMax(Integer vcBandwidthMax) {
    this.vcBandwidthMax = vcBandwidthMax;
  }


  public ServiceMetro ibxs(List<String> ibxs) {
    
    this.ibxs = ibxs;
    return this;
  }

  public ServiceMetro addIbxsItem(String ibxsItem) {
    if (this.ibxs == null) {
      this.ibxs = new ArrayList<>();
    }
    this.ibxs.add(ibxsItem);
    return this;
  }

   /**
   * Get ibxs
   * @return ibxs
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IBXS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getIbxs() {
    return ibxs;
  }


  @JsonProperty(JSON_PROPERTY_IBXS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIbxs(List<String> ibxs) {
    this.ibxs = ibxs;
  }


  public ServiceMetro inTrail(Boolean inTrail) {
    
    this.inTrail = inTrail;
    return this;
  }

   /**
   * Get inTrail
   * @return inTrail
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IN_TRAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getInTrail() {
    return inTrail;
  }


  @JsonProperty(JSON_PROPERTY_IN_TRAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInTrail(Boolean inTrail) {
    this.inTrail = inTrail;
  }


  public ServiceMetro displayName(String displayName) {
    
    this.displayName = displayName;
    return this;
  }

   /**
   * service metro display name
   * @return displayName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  public ServiceMetro sellerRegions(Map<String, String> sellerRegions) {
    
    this.sellerRegions = sellerRegions;
    return this;
  }

  public ServiceMetro putSellerRegionsItem(String key, String sellerRegionsItem) {
    if (this.sellerRegions == null) {
      this.sellerRegions = new HashMap<>();
    }
    this.sellerRegions.put(key, sellerRegionsItem);
    return this;
  }

   /**
   * Get sellerRegions
   * @return sellerRegions
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELLER_REGIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getSellerRegions() {
    return sellerRegions;
  }


  @JsonProperty(JSON_PROPERTY_SELLER_REGIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSellerRegions(Map<String, String> sellerRegions) {
    this.sellerRegions = sellerRegions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceMetro serviceMetro = (ServiceMetro) o;
    return Objects.equals(this.code, serviceMetro.code) &&
        Objects.equals(this.name, serviceMetro.name) &&
        Objects.equals(this.vcBandwidthMax, serviceMetro.vcBandwidthMax) &&
        Objects.equals(this.ibxs, serviceMetro.ibxs) &&
        Objects.equals(this.inTrail, serviceMetro.inTrail) &&
        Objects.equals(this.displayName, serviceMetro.displayName) &&
        Objects.equals(this.sellerRegions, serviceMetro.sellerRegions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, name, vcBandwidthMax, ibxs, inTrail, displayName, sellerRegions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceMetro {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    vcBandwidthMax: ").append(toIndentedString(vcBandwidthMax)).append("\n");
    sb.append("    ibxs: ").append(toIndentedString(ibxs)).append("\n");
    sb.append("    inTrail: ").append(toIndentedString(inTrail)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    sellerRegions: ").append(toIndentedString(sellerRegions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

