/*
 * Equinix Fabric API v4
 *
 * Contact: api-support@equinix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.fabric.v4.model;

import java.util.Objects;
import java.util.Arrays;
import com.equinix.openapi.fabric.v4.model.PriceLocation;
import com.equinix.openapi.fabric.v4.model.VirtualConnectionPriceASideAccessPointPort;
import com.equinix.openapi.fabric.v4.model.VirtualConnectionPriceAccessPointType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VirtualConnectionPriceASideAccessPoint
 */
@JsonPropertyOrder({
  VirtualConnectionPriceASideAccessPoint.JSON_PROPERTY_UUID,
  VirtualConnectionPriceASideAccessPoint.JSON_PROPERTY_TYPE,
  VirtualConnectionPriceASideAccessPoint.JSON_PROPERTY_LOCATION,
  VirtualConnectionPriceASideAccessPoint.JSON_PROPERTY_PORT
})
@JsonTypeName("VirtualConnectionPriceASide_accessPoint")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class VirtualConnectionPriceASideAccessPoint {
  public static final String JSON_PROPERTY_UUID = "uuid";
  private UUID uuid;

  public static final String JSON_PROPERTY_TYPE = "type";
  private VirtualConnectionPriceAccessPointType type;

  public static final String JSON_PROPERTY_LOCATION = "location";
  private PriceLocation location;

  public static final String JSON_PROPERTY_PORT = "port";
  private VirtualConnectionPriceASideAccessPointPort port;

  public VirtualConnectionPriceASideAccessPoint() {
  }

  public VirtualConnectionPriceASideAccessPoint uuid(UUID uuid) {
    
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getUuid() {
    return uuid;
  }


  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }


  public VirtualConnectionPriceASideAccessPoint type(VirtualConnectionPriceAccessPointType type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public VirtualConnectionPriceAccessPointType getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(VirtualConnectionPriceAccessPointType type) {
    this.type = type;
  }


  public VirtualConnectionPriceASideAccessPoint location(PriceLocation location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PriceLocation getLocation() {
    return location;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(PriceLocation location) {
    this.location = location;
  }


  public VirtualConnectionPriceASideAccessPoint port(VirtualConnectionPriceASideAccessPointPort port) {
    
    this.port = port;
    return this;
  }

   /**
   * Get port
   * @return port
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public VirtualConnectionPriceASideAccessPointPort getPort() {
    return port;
  }


  @JsonProperty(JSON_PROPERTY_PORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPort(VirtualConnectionPriceASideAccessPointPort port) {
    this.port = port;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirtualConnectionPriceASideAccessPoint virtualConnectionPriceASideAccessPoint = (VirtualConnectionPriceASideAccessPoint) o;
    return Objects.equals(this.uuid, virtualConnectionPriceASideAccessPoint.uuid) &&
        Objects.equals(this.type, virtualConnectionPriceASideAccessPoint.type) &&
        Objects.equals(this.location, virtualConnectionPriceASideAccessPoint.location) &&
        Objects.equals(this.port, virtualConnectionPriceASideAccessPoint.port);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, type, location, port);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirtualConnectionPriceASideAccessPoint {\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

