get:
  description: Provides information about learned routes for the VRF.
    The VRF builds this information dynamically though BGP from other
    routers in the network.
  summary: Retrieve learned L3 routes within the VRF
  operationId: getVrfLearnedRoutes
  tags:
    - VRFs
  parameters:
    - description: VRF UUID
      in: path
      name: id
      required: true
      schema:
        format: uuid
        type: string
  responses:
    "200":
      description: ok
      content:
        application/json:
          schema:
            $ref: '../../../components/schemas/VrfLearnedRoutesList.yaml'
    "403":
      description: forbidden
      content:
        application/json:
          schema:
            $ref: '../../../components/schemas/Error.yaml'
    "404":
      content:
        application/json:
          schema:
            $ref: '../../../components/schemas/Error.yaml'
      description: not found
