/*
 * Equinix Fabric API v4
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * The version of the OpenAPI document: 4.10
 * Contact: api-support@equinix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.fabric.v4.model;

import com.equinix.openapi.fabric.v4.model.ConnectedMetro;
import com.equinix.openapi.fabric.v4.model.GeoCoordinates;
import com.equinix.openapi.fabric.v4.model.GeoScopeType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Metro
 */
public class MetroTest {
    private final Metro model = new Metro();

    /**
     * Model tests for Metro
     */
    @Test
    public void testMetro() {
        // TODO: test Metro
    }

    /**
     * Test the property 'href'
     */
    @Test
    public void hrefTest() {
        // TODO: test href
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'equinixAsn'
     */
    @Test
    public void equinixAsnTest() {
        // TODO: test equinixAsn
    }

    /**
     * Test the property 'localVCBandwidthMax'
     */
    @Test
    public void localVCBandwidthMaxTest() {
        // TODO: test localVCBandwidthMax
    }

    /**
     * Test the property 'geoCoordinates'
     */
    @Test
    public void geoCoordinatesTest() {
        // TODO: test geoCoordinates
    }

    /**
     * Test the property 'connectedMetros'
     */
    @Test
    public void connectedMetrosTest() {
        // TODO: test connectedMetros
    }

    /**
     * Test the property 'geoScopes'
     */
    @Test
    public void geoScopesTest() {
        // TODO: test geoScopes
    }

}
