/*
 * Equinix Fabric API v4
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * The version of the OpenAPI document: 4.8
 * Contact: api-support@equinix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.fabric.v4.model;

import com.equinix.openapi.fabric.v4.model.SimplifiedLocation;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ServiceProfileAccessPointCOLO
 */
public class ServiceProfileAccessPointCOLOTest {
    private final ServiceProfileAccessPointCOLO model = new ServiceProfileAccessPointCOLO();

    /**
     * Model tests for ServiceProfileAccessPointCOLO
     */
    @Test
    public void testServiceProfileAccessPointCOLO() {
        // TODO: test ServiceProfileAccessPointCOLO
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'sellerRegion'
     */
    @Test
    public void sellerRegionTest() {
        // TODO: test sellerRegion
    }

    /**
     * Test the property 'sellerRegionDescription'
     */
    @Test
    public void sellerRegionDescriptionTest() {
        // TODO: test sellerRegionDescription
    }

    /**
     * Test the property 'crossConnectId'
     */
    @Test
    public void crossConnectIdTest() {
        // TODO: test crossConnectId
    }

}
