/*
 * Equinix Fabric API v4
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * The version of the OpenAPI document: 4.9
 * Contact: api-support@equinix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.fabric.v4.model;

import com.equinix.openapi.fabric.v4.model.ConnectivitySource;
import com.equinix.openapi.fabric.v4.model.LinkAggregationGroup;
import com.equinix.openapi.fabric.v4.model.VirtualPortConfiguration;
import com.equinix.openapi.fabric.v4.model.VirtualPortLocation;
import com.equinix.openapi.fabric.v4.model.VirtualPortRedundancy;
import com.equinix.openapi.fabric.v4.model.VirtualPortServiceType;
import com.equinix.openapi.fabric.v4.model.VirtualPortType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VirtualPortPrice
 */
public class VirtualPortPriceTest {
    private final VirtualPortPrice model = new VirtualPortPrice();

    /**
     * Model tests for VirtualPortPrice
     */
    @Test
    public void testVirtualPortPrice() {
        // TODO: test VirtualPortPrice
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'lag'
     */
    @Test
    public void lagTest() {
        // TODO: test lag
    }

    /**
     * Test the property 'physicalPortsQuantity'
     */
    @Test
    public void physicalPortsQuantityTest() {
        // TODO: test physicalPortsQuantity
    }

    /**
     * Test the property 'bandwidth'
     */
    @Test
    public void bandwidthTest() {
        // TODO: test bandwidth
    }

    /**
     * Test the property 'redundancy'
     */
    @Test
    public void redundancyTest() {
        // TODO: test redundancy
    }

    /**
     * Test the property 'connectivitySource'
     */
    @Test
    public void connectivitySourceTest() {
        // TODO: test connectivitySource
    }

    /**
     * Test the property 'serviceType'
     */
    @Test
    public void serviceTypeTest() {
        // TODO: test serviceType
    }

    /**
     * Test the property 'settings'
     */
    @Test
    public void settingsTest() {
        // TODO: test settings
    }

}
