# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Auto commit client updates

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TEST_DATA_UAT_QINQ_PORT: ${{ secrets.TEST_DATA_UAT_QINQ_PORT }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      
      - name: Set git user and generate files
        run: |
          git config --global user.name 'equinix-labs@auto-commit-workflow'
          git config --global user.email 'bot@equinix.noreply.github.com'
          git config advice.addIgnoredFile false
          git fetch
          echo -e "\nThis is executing for branch: ${GITHUB_REF##*/}."
          git checkout ${GITHUB_REF##*/}          
          make generate

      - name: Tests
        env:
          TEST_HOST_URL: https://uatapi.equinix.com
          CLIENT_ID: ${{ secrets.TEST_USER_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.TEST_USER_CLIENT_SECRET }}
          TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        shell: bash
        working-directory: ./equinix-openapi-fabric
        run: |-
          mvn clean package -DenvUrl=${{ env.TEST_HOST_URL }} -DuserName=${{ env.TEST_USER_NAME }} \
          -DuserPassword=${{ env.TEST_USER_PASSWORD }} -DclientId=${{ env.CLIENT_ID }} -DclientSecret=${{ env.CLIENT_SECRET }}

      - name: Commit to branch.
        run: |
          git add .
          echo -e "\nGit status:"
          echo `git status`
          cdate=`date`
          cmsg="Auto commit generated client changes - $cdate"
          echo -e "\nCommit message created : $cmsg"
          echo -e "\nCommitting if there are files to update in client dir:"
          echo `git commit -m "$cmsg"`
          echo `git push`     
