name: generate-release
# This workflow will generate changelog and release notes.
# Source: https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/.github/workflows/release.yml

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Release
        uses: cycjimmy/semantic-release-action@v4.0.0
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/exec@6.0.3
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SETTINGS_PATH: ${{ github.workspace }}/settings.xml
          GIT_AUTHOR_NAME: equinix-labs@auto-commit-workflow
          GIT_AUTHOR_EMAIL: bot@equinix.noreply.github.com
          GIT_COMMITTER_NAME: equinix-labs@auto-commit-workflow
          GIT_COMMITTER_EMAIL: bot@equinix.noreply.github.com
